name: Update index.html from Cloud Storage

on:
  schedule:
    - cron: '0 1 * * *' # Runs daily at 01:00 UTC
  workflow_dispatch:

jobs:
  update-file:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out repository
        uses: actions/checkout@v4

      # Step 2: Set up Google Cloud SDK
      - name: Set up Google Cloud SDK
#        uses: google-github-actions/setup-gcloud@v1
#        with:
#          service_account_key: ${{ secrets.TEST_STORAGE }}
#          project_id: maslometr

        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.TEST_STORAGE }}' # Replace with the name of your GitHub Actions secret

      # Step 3: Download index.html from GCS
      - name: Authenticate Google Cloud
        run: echo "${{ secrets.TEST_STORAGE }}" > /tmp/key.json && export GOOGLE_APPLICATION_CREDENTIALS=/tmp/key.json

      - name: Activate Service Account
        run: gcloud auth activate-service-account --key-file="/tmp/key.json"

      - name: Verify Google Cloud Authentication
        run: |
          gcloud auth list
          gsutil ls gs://ceny-masla/

      - name: Download index.html
        run: |
          gsutil -i test-storage@maslometr.iam.gserviceaccount.com cp gs://ceny-masla/index.html ./index.html

      # Step 4: Commit and push the updated index.html
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add index.html
          git commit -m "Update index.html from Cloud Storage [skip ci]" || echo "No changes to commit"
          git push
