name: Download File from GCS

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  download-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: 'latest'

    - name: Authenticate with GCS
      run: |
        echo "${{ secrets.GCS_KEY }}" > /tmp/gcs-key.json
        gcloud auth activate-service-account --key-file=/tmp/gcs-key.json

    - name: Download file from GCS
      run: |
        gsutil cp gs://maslo-prices/241222-maslo.csv ./241222-maslo.csv

    - name: Verify downloaded file
      run: |
        cat ./241222-maslo.csv

    - name: Cleanup
      run: |
        rm -f /tmp/gcs-key.json
